### PR TITLE
Removed console errors

### PR DESCRIPTION
**Pull request by natashapl**
### This pull request includes the following update:

- Removed console error on news pages
- Removed console error on submit an idea page

[PR Preview](https://federalist-37831b52-7633-429a-9a79-14298034dd54.sites.pages.cloud.gov/preview/gsa-tts/10x-website/fix-console-errors/)

### CODE REVIEW

**Comment by jonadecker** [comment]
Do we feel good about ensuring that this hasn't introduced any regression errors @natashapl ?

**Comment by natashapl** [comment]
Hi @jonadecker . Well, I deleted the script on the submit idea page and fixed syntax on the news page. I also clicked all the top nav links and didn't find any more issues. So, I think all is good. Let me know if you find any thing I may have missed.

**Review by jonadecker — COMMENTED** [review]
LGTM...I'm going to defer to @ethangardner to approve or request changes.

**Review by ethangardner — APPROVED** [review]
LGTM

**Pull request merged**
