### PR TITLE
Fixed border radius of feedback buttons

### PR DESCRIPTION
**Pull request by natashapl**
### This pull request includes the following update:

- Fixed the border-radius of feedback form buttons

[PR Preview](https://federalist-37831b52-7633-429a-9a79-14298034dd54.sites.pages.cloud.gov/preview/gsa-tts/10x-website/fix-feedback-border-radius/)

### CODE REVIEW

**Comment by jonathanbobel** [comment]
Can we fix the close button hover state with the PR too?
Screenshot 2024-10-31 at 9 32 40 AM

**Comment by natashapl** [comment]
Hi @jonathanbobel . I thought I fixed it per our conversation. The bottom left didn't have a border radius and so I added it so that way it's consistent. If that's not what you had in mind, please be specific with exactly how the hover state should be on the close button and I'll make the update. Thanks.

**Comment by jonadecker** [comment]
I think the side button looks great. @jonathanbobel are you looking for only the top right corner of the close button to be radius-cornered? It's balanced now in terms of padding, and has all radius corners, which I can totally live with but unsure if  you're looking specifically for something else.

**Comment by jonathanbobel** [comment]
@natashapl @jonadecker I meant the hover state in general, since it's not a button with a background color, I think it looks out of place here. As long as we don't remove the outline, we should be fine here in terns of accessibility, IMO.

**Comment by jonadecker** [comment]
@jonathanbobel that sounds right to me. @natashapl do you have what you need?

**Comment by jonadecker** [comment]
Question for @natashapl @jonathanbobel and @iamjolly ... upon closing the feedback modal, where should focus transfer to? Right now it goes back to the feedback button. Is that correct behavior?

**Comment by natashapl** [comment]
> Question for @natashapl @jonathanbobel and @iamjolly ... upon closing the feedback modal, where should focus transfer to? Right now it goes back to the feedback button. Is that correct behavior?

Hi @jonadecker . I'm a bit biased because that's the behavior I expected. I'll defer to @iamjolly or @jonathanbobel .

**Comment by iamjolly** [comment]
The current behavior is good as-is. Returning `focus` to the element that launched the modal is what is expected by users and what [the W3C recommends](https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/examples/dialog/).

**Review by jonadecker — APPROVED** [review]
💯

**Review by jonathanbobel — APPROVED** [review]
LGTM

**Pull request merged**
