### PR TITLE
203 - adding program logos to the cards on the home page

### PR DESCRIPTION
**Pull request by jonathanbobel**
Updating home page to have program logos in the card area

Reference: [#189](https://github.com/GSA-TTS/10x-website/issues/189)

[PR Preview](https://federalist-37831b52-7633-429a-9a79-14298034dd54.sites.pages.cloud.gov/preview/gsa-tts/10x-website/203-add-program-logos-to-featured-products/)

### CODE REVIEW

**Comment by jonathanbobel** [comment]
Not sure if we wanted to include any other logos before push to production

**Comment by jonadecker** [comment]
Based on our discusion, PRA Guide has an icon that doesn't appear to be a logo, and both PRA Guide and Site Scanning live under Digital.gov so should get an OK from them. Census xD would be the wildcard, and perhaps @willcahoe might know who to reach out to for an OK. They're using a PNG not an SVG (https://www.xd.gov/assets/img/xd-logo.png)

**Review by jonadecker — DISMISSED** [review]
Love it. Let's give the SS team a full 24 hours before moving forward.

**Comment by jonadecker** [comment]
Changes to SS LGTM @jonathanbobel

**Review by jonadecker — APPROVED** [review]
💯

**Pull request merged**
