### PR TITLE
10x home page updates to hero, idea submission CTA

### LINKED ISSUE #205: Tell us Once post -- Target date: Sept 3, 2024

### LINKED ISSUE #207: Copy change: FY25 idea evaluation
**User story**
As an Idea Submitter, I want it to be clear that while I can submit an idea at any time, 10x will not be evaluating new ideas in Q1 2025 (so I may not hear whether my idea has been selected for 12+ months).

**Definition of Done**

- [x] Copy appears in relevant places (top of Submit an idea; further down page near Submit an Idea button)

**Tasks**

- [x] Write copy
- [x] Approve copy
- [x] Publish copy

Also consider providing message on Qualtrics form or reply email.

### PR DESCRIPTION
**Pull request by jonadecker**
1. Updated hero to point to latest news item
2. Updated idea submission call to action (very bottom of page content)
3. Updated Submit an Idea page call to action
4. Updated excerpt on TUO news item

- [Home Page](https://federalist-37831b52-7633-429a-9a79-14298034dd54.sites.pages.cloud.gov/preview/gsa-tts/10x-website/JD-homepage-updates/)
- [Submit an Idea](https://federalist-37831b52-7633-429a-9a79-14298034dd54.sites.pages.cloud.gov/preview/gsa-tts/10x-website/JD-homepage-updates/submit-an-idea/#:~:text=After%20you%20fill%20out%20the%20form)
- [News landing](https://federalist-37831b52-7633-429a-9a79-14298034dd54.sites.pages.cloud.gov/preview/gsa-tts/10x-website/JD-homepage-updates/news/tags/Announcements/)

Closes #207  and makes hero consistent with latest news. Closes #205 excerpt cleanup

### CODE REVIEW

**Comment by jonadecker** [comment]
@marina-defrates for language review pre-merge please @jonathanbobel

**Comment by marina-defrates** [comment]
1. Hero looks good
2. and 3. Wondering whether the language at the bottom of the home page should mirror the language on the Submit an Idea page or vice versa or be combined (i.e. saying "no formal submission period but still accepting ideas" vs. "won't be evaluating new submissions until early FY26")? Thinking from the perspective of a potential idea author, the call to action feels a bit ambiguous - should I still submit my idea now or not?    
3. Can we bold the text "We've got a lot in the pipeline at the moment, and won't be evaluating new submissions until early FY26." instead of highlighting "After you fill out the form"

**Comment by jonadecker** [comment]
On 2 - @maomeara63 thoughts?

On 3 - the highlight isn't real, it's a result of deep linking to that header.  Are you asking to change the header? Or just to bold that sentence @marina-defrates

**Comment by jonadecker** [comment]
I've bolded just that sentence @marina-defrates. See if that's what you're looking for on the Submit an Idea page. No deep link this time:
https://federalist-37831b52-7633-429a-9a79-14298034dd54.sites.pages.cloud.gov/preview/gsa-tts/10x-website/JD-homepage-updates/submit-an-idea/

**Comment by jonadecker** [comment]
@marina-defrates for awareness, @maomeara63 for proofing, @jonathanbobel for review/merge please!

**Review by maomeara63 — APPROVED** [review]

**Review by jonathanbobel — APPROVED** [review]
LGTM

**Pull request merged**
